ydlidar_ros2_driver_node:
  ros__parameters:
    port: /dev/ttyUSB0
    frame_id: base_link          # ★ laser_frame → base_link 로 변경
    ignore_array: ""
    baudrate: 128000
    lidar_type: 1
    device_type: 0
    isSingleChannel: true
    intensity: false
    intensity_bit: 0
    sample_rate: 5
    abnormal_check_count: 4
    fixed_resolution: true
    reversion: false
    inverted: false
    auto_reconnect: true
    support_motor_dtr: false
    angle_max: 180.0
    angle_min: -180.0 
    range_max: 12.0
    range_min: 0.05             # 0.05 로 맞춰도 좋음
    frequency: 5.0
    invalid_range_is_inf: false
    debug: false
