slam_toolbox:
  ros__parameters:
    use_sim_time: false

    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ROS Parameters
    odom_frame: odom_rf2o
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    tracking_frame: base_link
    use_map_saver: true
    mode: mapping  # localization 로 바꾸면 위치추정 모드

    # odom / TF 관련
    use_odom: true              # ✅ rf2o(외부 odom)를 사용
    provide_odom_frame: false   # ✅ odom_rf2o -> base_link 는 rf2o가 TF publish
    publish_tf: true
    transform_publish_period: 0.02

    debug_logging: false
    throttle_scans: 20
    map_update_interval: 0.5
    resolution: 0.05
    min_laser_range: 0.05
    max_laser_range: 12.0
    minimum_time_interval: 0.2
    transform_timeout: 1.0
    tf_buffer_duration: 120.0
    stack_size_to_use: 40000000

    enable_interactive_mode: true

    # 이하 General / Correlation / Scan Matcher 파라미터들은 지금 그대로 두고 튜닝
    use_scan_matching: true
    use_stamped_pose: false
    use_scan_barycenter: true
    minimum_travel_distance: 0.05
    minimum_travel_heading: 0.05
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0
    do_loop_closing: false
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1

    loop_search_space_dimension: 4.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    distance_variance_penalty: 0.5
    angle_variance_penalty: 1.0

    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true
    min_pass_through: 2
    occupancy_threshold: 0.1
