rf20_laser_odometry:
  ros__parameters:
    laser_scan_topic: /scan
    odom_topic: /odom
    publish_tf: true
    base_frame_id: base_link
    odom_frame_id: odom
    freq: 10.0
    init_pose_from_topic: ""
    verbose: false
