slam_toolbox:
  ros__parameters:
    use_sim_time: false

    # 반드시 mapping
    mode: mapping

    # Frames
    map_frame: map
    odom_frame: odom_rf2o
    base_frame: base_link
    tracking_frame: base_link

    # Topics
    scan_topic: /scan
    odom_topic: /odom_rf2o   # 🔥 이게 빠져 있었음 (핵심)
    use_odom: true

    # IMU 반드시 사용
    use_imu: true
    imu_topic: /imu/data

    # TF
    provide_odom_frame: false
    publish_tf: true
    transform_publish_period: 0.05

    # SLAM 시작 조건 완화
    minimum_travel_distance: 0.0
    minimum_travel_heading: 0.0
    minimum_time_interval: 0.0

    throttle_scans: 1
    map_update_interval: 0.5

    resolution: 0.05
    min_laser_range: 0.05
    max_laser_range: 12.0

    use_scan_matching: true
    do_loop_closing: false

    debug_logging: true
